# 指定端口号
server:
  port: 9000

# 配置数据源
spring:
  application:
    name: security
  # 数据库连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.127.183:3306/testforsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Boco.123
  # Redis配置
  redis:
    host: 114.116.127.183
    port: 6379
    password: 123456
#    # 操作0号数据库，默认有16个数据库
#    database: 0
#    jedis:
#      pool:
#        max-active: 8 # 最大连接数
#        max-wait: 1ms # 连接池最大阻塞等待时间
#        max-idle: 4   # 连接池中的最大空闲连接
#        min-idle: 0   # 连接池中的最小空闲连接
    cache:
      redis:
        time-to-live: 60000 # 设置数据过期时间为半小时（ms）


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml