package com.sangeng.domain;

import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;



@TableName(value="acl_permission")
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AclPermission implements Serializable {
    private static final long serialVersionUID = -1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.pid
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.type
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.permission_value
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String permissionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.path
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.component
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.icon
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.status
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_permission.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.id
     *
     * @return the value of acl_permission.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.id
     *
     * @param id the value for acl_permission.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.pid
     *
     * @return the value of acl_permission.pid
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.pid
     *
     * @param pid the value for acl_permission.pid
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.name
     *
     * @return the value of acl_permission.name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.name
     *
     * @param name the value for acl_permission.name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.type
     *
     * @return the value of acl_permission.type
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.type
     *
     * @param type the value for acl_permission.type
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.permission_value
     *
     * @return the value of acl_permission.permission_value
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getPermissionValue() {
        return permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.permission_value
     *
     * @param permissionValue the value for acl_permission.permission_value
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setPermissionValue(String permissionValue) {
        this.permissionValue = permissionValue == null ? null : permissionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.path
     *
     * @return the value of acl_permission.path
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.path
     *
     * @param path the value for acl_permission.path
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.component
     *
     * @return the value of acl_permission.component
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.component
     *
     * @param component the value for acl_permission.component
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.icon
     *
     * @return the value of acl_permission.icon
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.icon
     *
     * @param icon the value for acl_permission.icon
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.status
     *
     * @return the value of acl_permission.status
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.status
     *
     * @param status the value for acl_permission.status
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.is_deleted
     *
     * @return the value of acl_permission.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.is_deleted
     *
     * @param isDeleted the value for acl_permission.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.gmt_create
     *
     * @return the value of acl_permission.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.gmt_create
     *
     * @param gmtCreate the value for acl_permission.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_permission.gmt_modified
     *
     * @return the value of acl_permission.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_permission.gmt_modified
     *
     * @param gmtModified the value for acl_permission.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}