package com.sangeng.domain;

import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
@TableName(value="acl_user")
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class User implements Serializable {
    private static final long serialVersionUID = -2L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.username
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.password
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.nick_name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.salt
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.token
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acl_user.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.id
     *
     * @return the value of acl_user.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.id
     *
     * @param id the value for acl_user.id
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.username
     *
     * @return the value of acl_user.username
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.username
     *
     * @param username the value for acl_user.username
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.password
     *
     * @return the value of acl_user.password
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.password
     *
     * @param password the value for acl_user.password
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.nick_name
     *
     * @return the value of acl_user.nick_name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.nick_name
     *
     * @param nickName the value for acl_user.nick_name
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.salt
     *
     * @return the value of acl_user.salt
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.salt
     *
     * @param salt the value for acl_user.salt
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.token
     *
     * @return the value of acl_user.token
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.token
     *
     * @param token the value for acl_user.token
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.is_deleted
     *
     * @return the value of acl_user.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.is_deleted
     *
     * @param isDeleted the value for acl_user.is_deleted
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.gmt_create
     *
     * @return the value of acl_user.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.gmt_create
     *
     * @param gmtCreate the value for acl_user.gmt_create
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acl_user.gmt_modified
     *
     * @return the value of acl_user.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acl_user.gmt_modified
     *
     * @param gmtModified the value for acl_user.gmt_modified
     *
     * @mbg.generated Mon Aug 01 11:42:44 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}